kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: flowlab
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30425
    hostPort: 4245
  - containerPort: 6443
    hostPort: 6443
- role: worker

